name: /home/fox/micromamba/envs/ecoli_microc
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - aom=3.8.2
  - asciitree=0.3.3
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - bedtools=2.31.1
  - bioframe=0.6.4
  - biopython=1.83
  - blas=1.1
  - blosc=1.21.5
  - bokeh=3.4.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - chromosight=1.6.3
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cooler=0.9.3
  - cooltools=0.7.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - deeptools=3.5.5
  - deeptoolsintervals=0.1.9
  - dill=0.3.8
  - distributed=2024.5.0
  - docopt=0.6.2
  - docutils=0.21.2
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gdbm=1.18
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - htslib=1.20
  - icu=73.2
  - idna=3.7
  - imagecodecs=2023.9.4
  - imageio=2.34.1
  - imagesize=1.4.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.2
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libdeflate=1.18
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libopenblas=0.3.27
  - libparquet=15.0.2
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - msgpack-python=1.0.7
  - multiprocess=0.70.16
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numba=0.59.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=2.0.0
  - packaging=24.0
  - pairix=0.3.8
  - pandas=2.2.2
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - perl=5.34.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.1
  - plotly=5.22.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py2bit=0.3.0
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pybedtools=0.10.0
  - pybigwig=0.3.22
  - pyfaidx=0.8.1.1
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysam=0.22.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pyvcf3=1.0.3
  - pywavelets=1.5.0
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - rav1e=0.6.6
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.31.0
  - rpds-py=0.18.1
  - s2n=1.4.12
  - samtools=1.20
  - scikit-image=0.22.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.5.1
  - simplejson=3.19.2
  - six=1.16.0
  - snappy=1.1.10
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.8
  - sphinxcontrib-devhelp=1.0.6
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.7
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - svt-av1=2.0.0
  - tabulate=0.9.0
  - tblib=3.0.0
  - tenacity=8.3.0
  - threadpoolctl=3.5.0
  - tifffile=2024.5.3
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucx=1.15.0
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.4.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - coolpuppy==1.1.0
      - cython==3.0.10
      - defusedxml==0.7.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - h11==0.14.0
      - h5sparse==0.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - json5==0.9.25
      - jsonpointer==2.4
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - m2r2==0.3.3.post2
      - mistune==0.8.4
      - more-itertools==10.2.0
      - multiprocessing-logging==0.3.4
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.20.0
      - pybbi==0.4.0
      - pycparser==2.22
      - python-json-logger==2.0.7
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - terminado==0.18.1
      - tinycss2==1.3.0
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.10
